[workspace]
members = [
    "flare-api",
    "flare-core",
    "flare-adapters",
    "flare-storage",
    "flare-worker",
    "flare-common",
]

resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.75"

[workspace.dependencies]
# --- 基础 ---
tokio = { version = "1.40", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uuid = { version = "1", features = ["v4"] }
config = "0.15"
dotenvy = "0.15"
futures-util = "0.3"

# --- Web / API ---
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors"] }

# --- 存储 ---
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
redis = { version = "0.25", features = ["tokio-comp"] }

# --- Kafka ---
rdkafka = { version = "0.38", features = ["tokio", "cmake-build"] }

# --- 模板 ---
tera = "1.19"
handlebars = "6.0"

# --- 监控 ---
prometheus = "0.13"

# --- 邮件 ---
lettre = { version = "0.11", default-features = false, features = ["tokio1-rustls", "builder", "ring", "rustls-native-certs", "smtp-transport"] }
async-trait = "0.1"

# --- http client ---
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }

