[workspace]
members = [
    "flare-api",
    "flare-core",
    "flare-adapters",
    "flare-storage",
    "flare-worker",
    "flare-common",
]

resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.75"

[workspace.dependencies]
# --- 基础 ---
tokio = { version = "1.40", features = ["rt-multi-thread", "macros", "time"] }
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
config = "0.14"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uuid = { version = "1", features = ["v4"] }

# --- Web / API ---
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["trace", "cors"] }

# --- 存储 ---
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
redis = { version = "0.25", features = ["tokio-comp"] }

# --- Kafka ---
rdkafka = { version = "0.36", features = ["tokio", "cmake-build"] }

# --- 模板 ---
tera = "1.19"
handlebars = "6.0"

# --- 监控 ---
prometheus = "0.13"